Problem 2 

In [10]:
import numpy as np
from scipy.optimize import fsolve

# R = np.array([[a1, 0.892, 0.423],
#               [a2, b2, c2],
#               [-0.186, b3, c3]])

# every row of a rotation matrix is a unit vector
# so in the first row, a1 should be
a1 = np.sqrt(1 - 0.892**2 - 0.423**2)

# a1 = 0.1594 or -0.1594


# similarly, the first column second element can be get from
a2 = np.sqrt(1 - a1**2 - 0.186**2)

# a2 = 0.9695 or -0.9695

# the first column cross second column should be +- the third column

####################### right-hand matrix ######################
# we will have the equation:
# a2 * b3 + 0.186 * b2 = +0.423

# the second column is a unit vector:
# 0.892**2 + b2**2 + b3**2 = 1


def equations(vars):
    b2, b3 = vars
    eq1 = -0.9695 * b3 + 0.186 * b2 - 0.423
    eq2 = 0.892**2 + b2**2 + b3**2 - 1
    return [eq1, eq2]


initial_guess = [10, 10]
solution = fsolve(equations, initial_guess)
b2, b3 = solution
print(b2,b3)


# solution 1
a1, a2 = -0.1594, 0.9695
b2, b3 = 0.2221, 0.3937
c1, c2, c3 = np.cross(np.array([a1, a2, -0.186]), np.array([0.892, b2, b3]))
# c2, c3 = -0.1032, -0.9002

R = np.array([[a1, 0.892, 0.423],
              [a2, b2, c2],
              [-0.186, b3, c3]])

print(np.linalg.det(R))
print(R)

# solution 2
a1, a2 = 0.1594, 0.9695
b2, b3 = -0.0606, 0.4479
c1, c2, c3 = np.cross(np.array([a1, a2, -0.186]), np.array([0.892, b2, b3]))
# c2, c3 = -0.2373  -0.8745

R = np.array([[a1, 0.892, 0.423],
              [a2, b2, c2],
              [-0.186, b3, c3]])

print(np.linalg.det(R))
print(R)

# solution 3
a1, a2 = 0.1594, -0.9695
b2, b3 = 0.2221, -0.3937
c1, c2, c3 = np.cross(np.array([a1, a2, -0.186]), np.array([0.892, b2, b3]))

R = np.array([[a1, 0.892, 0.423],
              [a2, b2, c2],
              [-0.186, b3, c3]])

print(np.linalg.det(R))
print(R)


# solution 4
a1, a2 = -0.1594, -0.9695
b2, b3 = -0.0606, -0.4479
c1, c2, c3 = np.cross(np.array([a1, a2, -0.186]), np.array([0.892, b2, b3]))

R = np.array([[a1, 0.892, 0.423],
              [a2, b2, c2],
              [-0.186, b3, c3]])

print(np.linalg.det(R))
print(R)



0.22213456477956192 -0.39369053218256983
0.999925539681316
[[ 0.1594      0.892       0.423     ]
 [-0.9695      0.2221     -0.10315622]
 [-0.186      -0.3937      0.90019674]]
0.9998991355079573
[[-0.1594      0.892       0.423     ]
 [-0.9695     -0.0606     -0.23730726]
 [-0.186      -0.4479      0.87445364]]
-0.00012369999999999048


In [22]:
import numpy as np
from scipy.optimize import fsolve

# R = np.array([[a1, 0.892, 0.423],
#               [a2, b2, c2],
#               [-0.186, b3, c3]])

def equations(vars):
    b2, b3 = vars
    eq1 = -0.9695 * b3 + 0.186 * b2 + 0.423
    eq2 = 0.892**2 + b2**2 + b3**2 - 1
    return [eq1, eq2]


initial_guess = [-10, -10]
solution = fsolve(equations, initial_guess)
b2, b3 = solution
print(b2, b3)

####################### left-hand matrix ######################
# we will have the equation:
# a2 * b3 + 0.186 * b2 = -0.423

# the second column is a unit vector:
# 0.892**2 + b2**2 + b3**2 = 1

# solution 1
a1, a2 = 0.1594, 0.9695
b2, b3 = -0.22213456477956026, - 0.39369053218257016
c1, c2, c3 = -np.cross(np.array([a1, a2, -0.186]), np.array([0.892, b2, b3]))

R = np.array([[a1, 0.892, 0.423],
              [a2, b2, c2],
              [-0.186, b3, c3]])

# print(np.linalg.det(R))
print(R)

# solution 2
a1, a2 = -0.1594, 0.9695
b2, b3 = 0.060665338065554644, - 0.4479461092111327
c1, c2, c3 = -np.cross(np.array([a1, a2, -0.186]), np.array([0.892, b2, b3]))

R = np.array([[a1, 0.892, 0.423],
              [a2, b2, c2],
              [-0.186, b3, c3]])

# print(np.linalg.det(R))
print(R)

# solution 3
a1, a2 = 0.1594, -0.9695
b2, b3 = 0.060665338065554644,  0.4479461092111327
c1, c2, c3 = -np.cross(np.array([a1, a2, -0.186]), np.array([0.892, b2, b3]))

R = np.array([[a1, 0.892, 0.423],
              [a2, b2, c2],
              [-0.186, b3, c3]])

# print(np.linalg.det(R))
print(R)

# solution 4
a1, a2 = -0.1594, -0.9695
b2, b3 = -0.2221345647795587, 0.39369053218257044
c1, c2, c3 = -np.cross(np.array([a1, a2, -0.186]), np.array([0.892, b2, b3]))

R = np.array([[a1, 0.892, 0.423],
              [a2, b2, c2],
              [-0.186, b3, c3]])

# print(np.linalg.det(R))
print(R)

-0.2221345647795587 0.39369053218257044
[[ 0.1594      0.892       0.423     ]
 [ 0.9695     -0.22213456  0.10315773]
 [-0.186      -0.39369053  0.90020225]]
[[-0.1594      0.892       0.423     ]
 [ 0.9695      0.06066534  0.23731461]
 [-0.186      -0.44794611  0.87446405]]
[[ 0.1594      0.892       0.423     ]
 [-0.9695      0.06066534  0.23731461]
 [-0.186       0.44794611 -0.87446405]]
[[-0.1594      0.892       0.423     ]
 [-0.9695     -0.22213456  0.10315773]
 [-0.186       0.39369053 -0.90020225]]


Problem 5c

In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

c = 0.25
t = np.linspace(0, 50, 5000)  # time array

d_x = np.cos(0.1 * t)
d_y = np.sin(0.12 * t)
d_z = np.sin(0.08 * t)

Ap_x = c * np.cos(t) + np.cos(0.1 * t)
Ap_y = c * np.sin(t) + np.sin(0.12 * t)
Ap_z = np.sin(0.08 * t)

# Plotting
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Robot position
ax.plot(d_x, d_y, d_z, label='Robot')

# A_p(t) position
ax.plot(Ap_x, Ap_y, Ap_z, label='p(t)')

# Labels and legend
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
ax.set_title('robot position and A_p(t)')
ax.legend()

# Show plot
plt.show()

Problem 5d

In [ ]:
# Define the gravity vector at t=1
gravity_vector_t1 = np.array([1.1, 0.9, -9.7])

# Define the rotation matrix R(t) as a function of t


def rotation_matrix(t):
    return np.array([
        [np.cos(t), -np.sin(t), 0],
        [np.sin(t), np.cos(t), 0],
        [0, 0, 1]
    ])


# Calculate the rotation matrix at t=1 and t=5
R_t1 = rotation_matrix(1)
R_t5 = rotation_matrix(5)

# The rotation matrix from t=1 to t=5 is the product of R(t=5) and the inverse of R(t=1)
# However, since R(t) is orthogonal, its inverse is equal to its transpose
rotation_change = R_t5.T @ R_t1

# Apply the rotation change to the gravity vector at t=1 to find the gravity vector at t=5
gravity_vector_t5 = rotation_change @ gravity_vector_t1

gravity_vector_t5